language: cpp
compiler: gcc
dist: trusty

install:
- ./.ci-local/travis-install.sh
- ./.ci/travis-prepare.sh

script:
- ./.ci/travis-build.sh

matrix:
  include:

  - env: BRBASE=7.0 UASDK=1.5.6
    addons: { apt: { packages: ["libgtest-dev"] } }

  - env: BRBASE=3.15 UASDK=1.5.6
    addons: { apt: { packages: ["libgtest-dev"] } }

  - env: BRBASE=7.0 UASDK=1.6.3 CMPLR=gcc-6
    dist: xenial
    addons: { apt: { packages: ["g++-6", "libgtest-dev"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BRBASE=3.15 UASDK=1.6.3 CMPLR=gcc-6
    dist: xenial
    addons: { apt: { packages: ["g++-6", "libgtest-dev"], sources: ["ubuntu-toolchain-r-test"] } }
