language: cpp
compiler: gcc
dist: xenial

install:
- ./.ci-local/travis-install.sh
- ./.ci/travis-prepare.sh

script:
- ./.ci/travis-build.sh

matrix:
  include:

  - env: BASE_BRANCH=7.0 UASDK=1.5.6
    dist: trusty

  - env: BASE_BRANCH=3.15 UASDK=1.5.6
    dist: trusty

  - env: BASE_BRANCH=7.0 UASDK=1.6.3
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BASE_BRANCH=3.15 UASDK=1.6.3
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }
